### ISSUE TITLE
Suport Setting On Ubuntu 20.04

### ISSUE THREAD

**Issue by Luongvgg** [security-companion/w3af#701]
Is there any way to install w4af on ubuntu 20.04 or kali?

**Comment by codders** [comment]
It should work just by following the installation instructions. Where are
you struggling?

Thanks,

Arthur

Dr.Port ***@***.***> schrieb am Di., 9. Jan. 2024, 09:04:

**Comment by Luongvgg** [comment]
sudo nano /etc/lsb-release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"


luong@w4af:~/w4af$ pip freeze
/usr/bin/pip:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point
adagio==0.2.4
aiohttp==3.9.1
aiosignal==1.3.1
antlr4-python3-runtime==4.11.1
appdirs==1.4.3
async-timeout==4.0.3
attrs==19.3.0
Automat==0.8.0
blinker==1.4
certifi==2019.11.28
chardet==3.0.4
Click==7.0
cloud-init==23.3.3
cloudpickle==3.0.0
colorama==0.4.3
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
contourpy==1.1.1
cryptography==2.8
cycler==0.12.1
Cython==3.0.7
darts==0.27.1
dbus-python==1.2.16
distlib==0.3.8
distro==1.4.0
distro-info==0.23+ubuntu1.1
entrypoints==0.3
filelock==3.13.1
fonttools==4.47.0
frozenlist==1.4.1
fs==2.4.16
fsspec==2023.12.2
fugue==0.8.7
fugue-sql-antlr==0.2.0
holidays==0.40
httplib2==0.14.0
hyperlink==19.0.0
idna==2.8
importlib-metadata==1.5.0
importlib-resources==6.1.1
incremental==16.10.1
Jinja2==2.10.1
joblib==1.3.2
jsonpatch==1.22
jsonpointer==2.0
jsonschema==3.2.0
keyring==18.0.1
kiwisolver==1.4.5
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
lightning-utilities==0.10.0
llvmlite==0.41.1
MarkupSafe==1.1.0
matplotlib==3.7.4
more-itertools==4.2.0
mpmath==1.3.0
multidict==6.0.4
netifaces==0.10.4
networkx==3.1
nfoursid==1.0.1
numba==0.58.1
numpy==1.24.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.101
nvidia-nvtx-cu12==12.1.105
oauthlib==3.1.0
packaging==23.2
pandas==1.5.3
patsy==0.5.6
pexpect==4.6.0
pillow==10.2.0
pipenv==2023.11.15
platformdirs==4.1.0
pmdarima==2.0.4
protobuf==4.25.1
pyarrow==14.0.2
pyasn1==0.4.2
pyasn1-modules==0.2.1
PyGObject==3.36.0
PyHamcrest==1.9.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyod==1.1.2
pyOpenSSL==19.0.0
pyparsing==3.1.1
pyrsistent==0.15.5
pyserial==3.4
python-apt==2.0.1+ubuntu0.20.4.1
python-dateutil==2.8.2
python-debian==0.1.36+ubuntu1.1
pytorch-lightning==2.1.3
pytz==2023.3.post1
PyYAML==6.0.1
qpd==0.4.4
requests==2.22.0
requests-unixsocket==0.2.0
scikit-learn==1.3.2
scipy==1.10.1
SecretStorage==2.3.1
service-identity==18.1.0
shap==0.44.0
simplejson==3.16.0
six==1.14.0
slicer==0.0.7
sos==4.5.6
sqlglot==20.8.0
ssh-import-id==5.10
statsforecast==1.7.1
statsmodels==0.14.1
sympy==1.12
systemd-python==234
tbats==1.1.3
tblib==3.0.0
tensorboardX==2.6.2.2
termcolor==2.4.0
threadpoolctl==3.2.0
torch==2.1.2
torchmetrics==1.2.1
tqdm==4.66.1
triad==0.9.3
triton==2.1.0
Twisted==18.9.0
typing-extensions==4.9.0
ubuntu-advantage-tools==20.3
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
utilsforecast==0.0.24
virtualenv==20.25.0
virtualenv-clone==0.3.0
wadllib==1.3.3
xarray==2023.1.0
xgboost==2.0.3
yarl==1.9.4
zipp==3.17.0
zope.interface==4.7.1


luong@w4af:~/w4af$ python --version
Python 3.8.10
luong@w4af:~/w4af$

Thank you very much for answering my question,The installation on kali is very smooth but I am trying to install w4af on ubuntu 20.04 (above is my system information). Currently I have this error:

luong@w4af:~/w4af$ ./w4af_console
Traceback (most recent call last):
   File "./w4af_console", line 13, prints <module>
     from w4af.core.ui.console.console_ui import ConsoleUI
   File "/home/luong/w4af/w4af/core/ui/console/console_ui.py", line 35, print <module>
     from w4af.core.ui.console.rootMenu import rootMenu
   File "/home/luong/w4af/w4af/core/ui/console/rootMenu.py", line 32, print <module>
     from w4af.core.ui.console.menu import menu
   File "/home/luong/w4af/w4af/core/ui/console/menu.py", line 24, print <module>
     import w4af.core.data.kb.knowledge_base as kb
   File "/home/luong/w4af/w4af/core/data/kb/knowledge_base.py", line 30, print <module>
     from darts.lib.utils.lru import SynchronizedLRUDict
ModuleNotFoundError: No module named 'darts.lib'

I tried to install darts and darts.lib but it didn't work:

luong@w4af:~/w4af$ pip freeze | grep darts.lib
/usr/bin/pip:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
   from pkg_resources import load_entry_point
luong@w4af:~/w4af$ pip install darts.lib
/usr/bin/pip:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
   from pkg_resources import load_entry_point
ERROR: Could not find a version that satisfies the requirement darts.lib (from versions: none)
ERROR: No matching distribution found for darts.lib
luong@w4af:~/w4af$

Hope to get your response soon. Thank you very much!

**Comment by codders** [comment]
Hi again @Luongvgg,

Are you following the instructions [in the README](https://github.com/w4af/w4af?tab=readme-ov-file#installation)? If you are installing the python libraries with Pipenv, you shouldn't have a problem.
